### ISSUE TITLE
Vendor data present

### ISSUE THREAD

**Issue by mensfeld** [devmehq/devme-sdk-ruby#6]
Hey there,

My name is Maciej Mensfeld and I run security & quality assessment for Ruby libraries using WhiteSource Diffend.io.

While reviewing the changes for this lib, I noticed, that the vendor directory is being included.

Is this needed? Usually, it's added by mistake and causes:

a) confusion
b) problems when tracking changes
c) extensive library size

ref: [LINK](https://my.diffend.io/gems/devme-sdk-ruby/1.0.0)

If the presence of vendor data is valid I would love the reasoning. Thanks!

**Comment by meabed** [comment]
Thank you @mensfeld 
Yes it was added by mistake, and I have removed it latest build.

**Comment by mensfeld** [comment]
99,885441707% size reduction. Nice!
